import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/side-bar";
import { ViewTransitions } from "next-view-transitions";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Page",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.webp",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={`${inter.className} flex min-h-screen`}>
          <SideBar />
          <main className="container mx-auto flex-1 px-5 py-10 space-y-5">
            {children}
          </main>
          <Toaster />
        </body>
      </html>
    </ViewTransitions>
  );
}
